version: '3.9'
services:
  backend:
    build:
      context: ./flask_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./flask_backend:/app
      - ./models:/app/models
  frontend:
    build:
      context: ./bcv-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./bcv-frontend:/app
    depends_on:
      - backend
